[project]
name = "tabpfn-rs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.1",
    "tabpfn>=2.1.2",
    "torch>=2.8.0",
]
